### ISSUE TITLE
Ability to customise version of Terraform installed

### ISSUE THREAD

**Issue by chris-crone** [deislabs/porter-terraform#41]
Playing with this mixin on Kubernetes, I found one area of friction is storing the Terraform state. Either one would need to copy the state file between CNAB actions or use some remote backend.

With Terraform 0.13, currently there's an RC out, a [Kubernetes secret backend will be added](https://github.com/hashicorp/terraform/pull/19525) which makes this a lot less painful.

As the version of Terraform is currently [hardcoded in the mixin](https://github.com/deislabs/porter-terraform/blob/main/pkg/terraform/build.go#L7), it's not easy to use this feature as one would have to rebuild the mixin. I think that wanting to specify versions of tools will actually be quite common, would it make sense to add a mixin config that allows this?

**Comment by vdice** [comment]
For prior art, see https://github.com/deislabs/porter-helm#mixin-configuration (and PR that implemented the feature: https://github.com/deislabs/porter-helm/pull/64)

Allowing in the `porter.yaml` and entry like:
```yaml
mixins:
  - terraform:
      clientVersion: 0.12.29
```
(where the terraform version `0.12.29` is downloaded/used in the resulting bundle invocation image.)
