### ISSUE TITLE
Run terraform init at invocation image build time

### ISSUE THREAD

**Issue by vdice** [deislabs/porter-terraform#6]
Currently, we (re)-run `terraform init` at run time before any lifecycle action (install, uninstall, etc.)

Once we have the context necessary to do so, let's consider running `terraform init` at invocation image build time.  See https://github.com/deislabs/porter-terraform/pull/3#discussion_r274564588 for the genesis of this idea.  

Porter ticket in https://github.com/deislabs/porter/issues/262

For due diligence, here are the init docs: https://www.terraform.io/docs/commands/init.html

**Comment by oleksiidzhulai** [comment]
+1

leaving 'terraform init' at run time means inability to execute for air gapped environments, since terraform plugins are fetched during that time

**Comment by vdice** [comment]
@oleksiidzhulai thank you for the reminder on this ticket.  I'll start on this work...
